# Generated by Django 2.0 on 2018-02-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='O campo de nome deve conter o nome de uma paragem.', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='O valor do campo deve ser uma latitude WGS 84 válida.', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='O valor do campo deve ser uma latitude WGS 84 válida.', max_digits=9)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stops', to='places.Place')),
            ],
        ),
    ]
