# Generated by Django 2.0 on 2017-12-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('lisboa', 'Lisboa');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('porto', 'Porto');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('setubal', 'Setúbal');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('braga', 'Braga');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('aveiro', 'Aveiro');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('leiria', 'Leiria');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('santarem', 'Santarém');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('faro', 'Faro');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('coimbra', 'Coimbra');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('viseu', 'Viseu');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('viana-do-castelo', 'Viana do Castelo');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('vila-real', 'Vila Real');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('castelo-branco', 'Castelo Branco');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('evora', 'Évora');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('guarda', 'Guarda');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('beja', 'Beja');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('braganca', 'Bragança');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('portalegre', 'Portalegre');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('regiao-autonoma-da-madeira', 'Região Autónoma da Madeira');".format('districts')),
        migrations.RunSQL("INSERT INTO {0}_district (slug, name) VALUES ('regiao-autonoma-dos-acores', 'Região Autónoma dos Açores');".format('districts')),
    ]
