# Generated by Django 2.0 on 2018-02-15 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0002_auto_20180215_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='O campo de nome deve conter o nome curto da rota.', max_length=20)),
                ('long_name', models.CharField(help_text='O campo de nome deve conter o nome longo da rota.', max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'Trem'), (1, 'Metro'), (2, 'Comboio'), (3, 'Autocarro'), (4, 'Ferry'), (5, 'Elétrico'), (6, 'Teleférico'), (7, 'Funicular')], help_text='O tipo de transporte usado na rota')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='routes', to='agencies.Agency')),
            ],
        ),
    ]
