# Generated by Django 2.0 on 2017-12-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'abrantes' as slug, 'Abrantes' as name, district.id FROM districts_district as district WHERE district.slug = 'santarem';".format(
                'cities')),
    ]
