# Generated by Django 2.0 on 2017-12-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='districts.District')),
            ],
        ),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'abrantes' as slug, 'Abrantes' as name, district.id FROM districts_district as district WHERE district.slug = 'santarem';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'agualva-cacem' as slug, 'Agualva-Cacém' as name, district.id FROM districts_district as district WHERE district.slug = 'lisboa';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'agueda' as slug, 'Águeda' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'albergaria-a-velha' as slug, 'Albergaria-a-Velha' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'albufeira' as slug, 'Albufeira' as name, district.id FROM districts_district as district WHERE district.slug = 'faro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'alcacer-do-sal' as slug, 'Alcácer do Sal' as name, district.id FROM districts_district as district WHERE district.slug = 'setubal';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'alcobaca' as slug, 'Alcobaça' as name, district.id FROM districts_district as district WHERE district.slug = 'leiria';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'alfena' as slug, 'Alfena' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'almada' as slug, 'Almada' as name, district.id FROM districts_district as district WHERE district.slug = 'setubal';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'almeirim' as slug, 'Almeirim' as name, district.id FROM districts_district as district WHERE district.slug = 'santarem';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'alverca-do-ribatejo' as slug, 'Alverca do Ribatejo' as name, district.id FROM districts_district as district WHERE district.slug = 'lisboa';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'amadora' as slug, 'Amadora' as name, district.id FROM districts_district as district WHERE district.slug = 'lisboa';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'amarante' as slug, 'Amarante' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'amora' as slug, 'Amora' as name, district.id FROM districts_district as district WHERE district.slug = 'setubal';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'anadia' as slug, 'Anadia' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'angra-do-heroismo' as slug, 'Angra do Heroísmo' as name, district.id FROM districts_district as district WHERE district.slug = 'regiao-autonoma-dos-acores';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'aveiro' as slug, 'Aveiro' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'barcelos' as slug, 'Barcelos' as name, district.id FROM districts_district as district WHERE district.slug = 'braga';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'barreiro' as slug, 'Barreiro' as name, district.id FROM districts_district as district WHERE district.slug = 'setubal';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'beja' as slug, 'Beja' as name, district.id FROM districts_district as district WHERE district.slug = 'beja';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'borba' as slug, 'Borba' as name, district.id FROM districts_district as district WHERE district.slug = 'evora';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'braga' as slug, 'Braga' as name, district.id FROM districts_district as district WHERE district.slug = 'braga';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'braganca' as slug, 'Bragança' as name, district.id FROM districts_district as district WHERE district.slug = 'braganca';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'caldas-da-rainha' as slug, 'Caldas da Rainha' as name, district.id FROM districts_district as district WHERE district.slug = 'leiria';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'camara-de-lobos' as slug, 'Câmara de Lobos' as name, district.id FROM districts_district as district WHERE district.slug = 'regiao-autonoma-da-madeira';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'canico' as slug, 'Caniço' as name, district.id FROM districts_district as district WHERE district.slug = 'regiao-autonoma-da-madeira';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'cantanhede' as slug, 'Cantanhede' as name, district.id FROM districts_district as district WHERE district.slug = 'coimbra';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'cartaxo' as slug, 'Cartaxo' as name, district.id FROM districts_district as district WHERE district.slug = 'santarem';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'castelo-branco' as slug, 'Castelo Branco' as name, district.id FROM districts_district as district WHERE district.slug = 'castelo-branco';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'chaves' as slug, 'Chaves' as name, district.id FROM districts_district as district WHERE district.slug = 'vila-real';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'coimbra' as slug, 'Coimbra' as name, district.id FROM districts_district as district WHERE district.slug = 'coimbra';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'costa-da-caparica' as slug, 'Costa da Caparica' as name, district.id FROM districts_district as district WHERE district.slug = 'setubal';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'covilha' as slug, 'Covilhã' as name, district.id FROM districts_district as district WHERE district.slug = 'castelo-branco';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'elvas' as slug, 'Elvas' as name, district.id FROM districts_district as district WHERE district.slug = 'portalegre';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'entroncamento' as slug, 'Entroncamento' as name, district.id FROM districts_district as district WHERE district.slug = 'santarem';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'ermesinde' as slug, 'Ermesinde' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'esmoriz' as slug, 'Esmoriz' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'espinho' as slug, 'Espinho' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'esposende' as slug, 'Esposende' as name, district.id FROM districts_district as district WHERE district.slug = 'braga';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'estarreja' as slug, 'Estarreja' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'estremoz' as slug, 'Estremoz' as name, district.id FROM districts_district as district WHERE district.slug = 'evora';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'evora' as slug, 'Évora' as name, district.id FROM districts_district as district WHERE district.slug = 'evora';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'fafe' as slug, 'Fafe' as name, district.id FROM districts_district as district WHERE district.slug = 'braga';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'faro' as slug, 'Faro' as name, district.id FROM districts_district as district WHERE district.slug = 'faro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'fatima' as slug, 'Fátima' as name, district.id FROM districts_district as district WHERE district.slug = 'santarem';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'felgueiras' as slug, 'Felgueiras' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'figueira-da-foz' as slug, 'Figueira da Foz' as name, district.id FROM districts_district as district WHERE district.slug = 'coimbra';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'fiaes' as slug, 'Fiães' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'freamunde' as slug, 'Freamunde' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'funchal' as slug, 'Funchal' as name, district.id FROM districts_district as district WHERE district.slug = 'regiao-autonoma-da-madeira';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'fundao' as slug, 'Fundão' as name, district.id FROM districts_district as district WHERE district.slug = 'castelo-branco';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'gafanha-da-nazare' as slug, 'Gafanha da Nazaré' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'gandra' as slug, 'Gandra' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'gondomar' as slug, 'Gondomar' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'gouveia' as slug, 'Gouveia' as name, district.id FROM districts_district as district WHERE district.slug = 'guarda';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'guarda' as slug, 'Guarda' as name, district.id FROM districts_district as district WHERE district.slug = 'guarda';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'guimaraes' as slug, 'Guimarães' as name, district.id FROM districts_district as district WHERE district.slug = 'braga';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'horta' as slug, 'Horta' as name, district.id FROM districts_district as district WHERE district.slug = 'regiao-autonoma-dos-acores';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'ilhavo' as slug, 'Ílhavo' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'lagoa' as slug, 'Lagoa' as name, district.id FROM districts_district as district WHERE district.slug = 'regiao-autonoma-dos-acores';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'lagoa' as slug, 'Lagoa' as name, district.id FROM districts_district as district WHERE district.slug = 'faro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'lagos' as slug, 'Lagos' as name, district.id FROM districts_district as district WHERE district.slug = 'faro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'lamego' as slug, 'Lamego' as name, district.id FROM districts_district as district WHERE district.slug = 'viseu';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'leiria' as slug, 'Leiria' as name, district.id FROM districts_district as district WHERE district.slug = 'leiria';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'lisboa' as slug, 'Lisboa' as name, district.id FROM districts_district as district WHERE district.slug = 'lisboa';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'lixa' as slug, 'Lixa' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'loule' as slug, 'Loulé' as name, district.id FROM districts_district as district WHERE district.slug = 'faro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'loures' as slug, 'Loures' as name, district.id FROM districts_district as district WHERE district.slug = 'lisboa';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'lourosa' as slug, 'Lourosa' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'macedo-de-cavaleiros' as slug, 'Macedo de Cavaleiros' as name, district.id FROM districts_district as district WHERE district.slug = 'braganca';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'machico' as slug, 'Machico' as name, district.id FROM districts_district as district WHERE district.slug = 'regiao-autonoma-da-madeira';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'maia' as slug, 'Maia' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'mangualde' as slug, 'Mangualde' as name, district.id FROM districts_district as district WHERE district.slug = 'viseu';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'marco-de-canaveses' as slug, 'Marco de Canaveses' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'marinha-grande' as slug, 'Marinha Grande' as name, district.id FROM districts_district as district WHERE district.slug = 'leiria';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'matosinhos' as slug, 'Matosinhos' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'mealhada' as slug, 'Mealhada' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'meda' as slug, 'Mêda' as name, district.id FROM districts_district as district WHERE district.slug = 'guarda';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'miranda-do-douro-miranda-de-l-douro' as slug, 'Miranda do Douro / Miranda de l Douro' as name, district.id FROM districts_district as district WHERE district.slug = 'braganca';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'mirandela' as slug, 'Mirandela' as name, district.id FROM districts_district as district WHERE district.slug = 'braganca';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'montemor-o-novo' as slug, 'Montemor-o-Novo' as name, district.id FROM districts_district as district WHERE district.slug = 'evora';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'montijo' as slug, 'Montijo' as name, district.id FROM districts_district as district WHERE district.slug = 'setubal';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'moura' as slug, 'Moura' as name, district.id FROM districts_district as district WHERE district.slug = 'beja';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'odivelas' as slug, 'Odivelas' as name, district.id FROM districts_district as district WHERE district.slug = 'lisboa';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'olhao-da-restauracao' as slug, 'Olhão da Restauração' as name, district.id FROM districts_district as district WHERE district.slug = 'faro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'oliveira-de-azemeis' as slug, 'Oliveira de Azeméis' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'oliveira-do-bairro' as slug, 'Oliveira do Bairro' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'oliveira-do-hospital' as slug, 'Oliveira do Hospital' as name, district.id FROM districts_district as district WHERE district.slug = 'coimbra';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'ourem' as slug, 'Ourém' as name, district.id FROM districts_district as district WHERE district.slug = 'santarem';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'ovar' as slug, 'Ovar' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'pacos-de-ferreira' as slug, 'Paços de Ferreira' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'paredes' as slug, 'Paredes' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'penafiel' as slug, 'Penafiel' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'peniche' as slug, 'Peniche' as name, district.id FROM districts_district as district WHERE district.slug = 'leiria';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'peso-da-regua' as slug, 'Peso da Régua' as name, district.id FROM districts_district as district WHERE district.slug = 'vila-real';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'pinhel' as slug, 'Pinhel' as name, district.id FROM districts_district as district WHERE district.slug = 'guarda';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'pombal' as slug, 'Pombal' as name, district.id FROM districts_district as district WHERE district.slug = 'leiria';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'ponta-delgada' as slug, 'Ponta Delgada' as name, district.id FROM districts_district as district WHERE district.slug = 'regiao-autonoma-dos-acores';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'ponte-de-sor' as slug, 'Ponte de Sor' as name, district.id FROM districts_district as district WHERE district.slug = 'portalegre';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'portalegre' as slug, 'Portalegre' as name, district.id FROM districts_district as district WHERE district.slug = 'portalegre';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'portimao' as slug, 'Portimão' as name, district.id FROM districts_district as district WHERE district.slug = 'faro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'porto' as slug, 'Porto' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'povoa-de-santa-iria' as slug, 'Póvoa de Santa Iria' as name, district.id FROM districts_district as district WHERE district.slug = 'lisboa';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'povoa-de-varzim' as slug, 'Póvoa de Varzim' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'praia-da-vitoria' as slug, 'Praia da Vitória' as name, district.id FROM districts_district as district WHERE district.slug = 'regiao-autonoma-dos-acores';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'quarteira' as slug, 'Quarteira' as name, district.id FROM districts_district as district WHERE district.slug = 'faro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'queluz' as slug, 'Queluz' as name, district.id FROM districts_district as district WHERE district.slug = 'lisboa';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'rebordosa' as slug, 'Rebordosa' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'reguengos-de-monsaraz' as slug, 'Reguengos de Monsaraz' as name, district.id FROM districts_district as district WHERE district.slug = 'evora';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'ribeira-grande' as slug, 'Ribeira Grande' as name, district.id FROM districts_district as district WHERE district.slug = 'regiao-autonoma-dos-acores';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'rio-maior' as slug, 'Rio Maior' as name, district.id FROM districts_district as district WHERE district.slug = 'santarem';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'rio-tinto' as slug, 'Rio Tinto' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'sabugal' as slug, 'Sabugal' as name, district.id FROM districts_district as district WHERE district.slug = 'guarda';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'sacavem' as slug, 'Sacavém' as name, district.id FROM districts_district as district WHERE district.slug = 'lisboa';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'samora-correia' as slug, 'Samora Correia' as name, district.id FROM districts_district as district WHERE district.slug = 'santarem';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'santa-comba-dao' as slug, 'Santa Comba Dão' as name, district.id FROM districts_district as district WHERE district.slug = 'viseu';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'santa-cruz' as slug, 'Santa Cruz' as name, district.id FROM districts_district as district WHERE district.slug = 'regiao-autonoma-da-madeira';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'santa-maria-da-feira' as slug, 'Santa Maria da Feira' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'santana' as slug, 'Santana' as name, district.id FROM districts_district as district WHERE district.slug = 'regiao-autonoma-da-madeira';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'santarem' as slug, 'Santarém' as name, district.id FROM districts_district as district WHERE district.slug = 'santarem';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'santiago-do-cacem' as slug, 'Santiago do Cacém' as name, district.id FROM districts_district as district WHERE district.slug = 'setubal';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'santo-tirso' as slug, 'Santo Tirso' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'sao-joao-da-madeira' as slug, 'São João da Madeira' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'sao-mamede-de-infesta' as slug, 'São Mamede de Infesta' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'sao-pedro-do-sul' as slug, 'São Pedro do Sul' as name, district.id FROM districts_district as district WHERE district.slug = 'viseu';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'lordelo' as slug, 'Lordelo' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'seia' as slug, 'Seia' as name, district.id FROM districts_district as district WHERE district.slug = 'guarda';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'seixal' as slug, 'Seixal' as name, district.id FROM districts_district as district WHERE district.slug = 'setubal';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'senhora-da-hora' as slug, 'Senhora da Hora' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'serpa' as slug, 'Serpa' as name, district.id FROM districts_district as district WHERE district.slug = 'beja';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'setubal' as slug, 'Setúbal' as name, district.id FROM districts_district as district WHERE district.slug = 'setubal';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'silves' as slug, 'Silves' as name, district.id FROM districts_district as district WHERE district.slug = 'faro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'sines' as slug, 'Sines' as name, district.id FROM districts_district as district WHERE district.slug = 'setubal';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'tarouca' as slug, 'Tarouca' as name, district.id FROM districts_district as district WHERE district.slug = 'viseu';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'tavira' as slug, 'Tavira' as name, district.id FROM districts_district as district WHERE district.slug = 'faro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'tomar' as slug, 'Tomar' as name, district.id FROM districts_district as district WHERE district.slug = 'santarem';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'tondela' as slug, 'Tondela' as name, district.id FROM districts_district as district WHERE district.slug = 'viseu';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'torres-novas' as slug, 'Torres Novas' as name, district.id FROM districts_district as district WHERE district.slug = 'santarem';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'torres-vedras' as slug, 'Torres Vedras' as name, district.id FROM districts_district as district WHERE district.slug = 'lisboa';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'trancoso' as slug, 'Trancoso' as name, district.id FROM districts_district as district WHERE district.slug = 'guarda';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'trofa' as slug, 'Trofa' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'valbom' as slug, 'Valbom' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'vale-de-cambra' as slug, 'Vale de Cambra' as name, district.id FROM districts_district as district WHERE district.slug = 'aveiro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'valenca' as slug, 'Valença' as name, district.id FROM districts_district as district WHERE district.slug = 'viana-do-castelo';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'valongo' as slug, 'Valongo' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'valpacos' as slug, 'Valpaços' as name, district.id FROM districts_district as district WHERE district.slug = 'vila-real';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'vendas-novas' as slug, 'Vendas Novas' as name, district.id FROM districts_district as district WHERE district.slug = 'evora';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'viana-do-castelo' as slug, 'Viana do Castelo' as name, district.id FROM districts_district as district WHERE district.slug = 'viana-do-castelo';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'vila-baleira' as slug, 'Vila Baleira' as name, district.id FROM districts_district as district WHERE district.slug = 'regiao-autonoma-da-madeira';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'vila-do-conde' as slug, 'Vila do Conde' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'vila-franca-de-xira' as slug, 'Vila Franca de Xira' as name, district.id FROM districts_district as district WHERE district.slug = 'lisboa';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'vila-nova-de-famalicao' as slug, 'Vila Nova de Famalicão' as name, district.id FROM districts_district as district WHERE district.slug = 'braga';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'vila-nova-de-foz-coa' as slug, 'Vila Nova de Foz Côa' as name, district.id FROM districts_district as district WHERE district.slug = 'guarda';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'vila-nova-de-gaia' as slug, 'Vila Nova de Gaia' as name, district.id FROM districts_district as district WHERE district.slug = 'porto';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'vila-nova-de-santo-andre' as slug, 'Vila Nova de Santo André' as name, district.id FROM districts_district as district WHERE district.slug = 'setubal';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'vila-real' as slug, 'Vila Real' as name, district.id FROM districts_district as district WHERE district.slug = 'vila-real';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'vila-real-de-santo-antonio' as slug, 'Vila Real de Santo António' as name, district.id FROM districts_district as district WHERE district.slug = 'faro';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'viseu' as slug, 'Viseu' as name, district.id FROM districts_district as district WHERE district.slug = 'viseu';".format(
                'cities')),
        migrations.RunSQL(
            "INSERT INTO {0}_city (slug, name, district_id) SELECT 'vizela' as slug, 'Vizela' as name, district.id FROM districts_district as district WHERE district.slug = 'braga';".format(
                'cities')),
    ]
