# Generated by Django 2.0 on 2018-02-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='map_data',
            field=models.FileField(upload_to='maps', verbose_name='Ficheiro'),
        ),
    ]
