# Generated by Django 2.0 on 2018-02-15 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        ('stops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stoptime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_sequence', models.PositiveIntegerField(default=1)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stoptimes', to='stops.Stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stoptimes', to='trips.Trip')),
            ],
        ),
    ]
