# Generated by Django 2.0 on 2018-02-15 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        ('calendardates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendardate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips', to='calendardates.CalendarDate')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips', to='routes.Route')),
            ],
        ),
    ]
